config/routes.rb
Rails.application.routes.draw do
  resources :schedules

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.order("date")
    @year = params[:year]
    @month = params[:month]

  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    p params[:years]
    p params[:month]
    p params[:day]
    p params[:id]
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:plan, :date, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shedule</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plan %><br>
    <%= f.text_area :plan, :size=>"40x5" %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schedules&#9825;</h1>

<%if @year.nil?%>
  <%@year = Date.today.year%>
  <%@month = Date.today.month%>
<% end %>
<% special =  Time.zone.local(@year,@month)%>


<h3><%=special.year%>年<%=special.month%>月</h3>

<h2>&nbsp;&#9756;&nbsp;<%= link_to"#{special.prev_month.month}月", schedules_path(year: special.prev_month.year,month: special.prev_month.month)%>
&lt;&nbsp;<%="#{special.month}月"%>
&gt;&nbsp;<%= link_to"#{special.next_month.month}月", schedules_path(year: special.next_month.year,month: special.next_month.month)%>
&#9758;


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10032;
<%= link_to"今月", schedules_path(year: Date.today.year,month: Date.today.month)%>
&#10032;

</h2>


<table border = "1" cellspacing="0">
  <thead>
    <tr>
      <th width = "40">Date</th>
      <th width = "50">WDay</th>
      <th width = "200" border = "1" cellspacing="0">Plan</th>
      <th width = "300">Image</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>  
      <% 
      endday =special.end_of_month
        x = 0...endday.day
        x.each do |y|
          
          today=special.beginning_of_month + y.days%>

          <tr>
            <td height="100" align="center"><%= today.day %>日</td>

            <%arr = ["日","月","火","水","木","金","土"]%>
            <td height="100" align="center" border = "1" cellspacing="0"><%=arr[today.wday]%>曜日</td>

            <%@schedules.each do |schedule| %>
             
              <%if today.year == schedule.date.year && today.month == schedule.date.month && today.day == schedule.date.day%>
                <%if schedule.plan.empty?%>
                  <td width = "50"><%= "予定なし" %></td>
                <%else%>
                  <td width = "50"><%= simple_format(h schedule.plan) %></td>
                <%end%>
                <td align="center"><img src="<%= schedule.image %>" height="100"></td>
                <td><%= link_to 'Show', schedule %>
                <%= link_to 'Edit', edit_schedule_path(schedule) %>
                <%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>

             
              <%end%>

            <% end %>
          </tr>
        <% end %>


  </tbody>

</table>

<br>
<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plan:</strong>
  <%= simple_format(h @schedule.plan) %>
</p>

<p>
  <strong>Date:</strong>
  <%= @schedule.date %>
</p>

<p>
  <strong>Image:</strong>
</p>
<p>
  <img src="<%= @schedule.image %>" width="200">
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>